//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tble_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tble_Product()
        {
            this.Tble_Cart = new HashSet<Tble_Cart>();
            this.Tble_OrderDetails = new HashSet<Tble_OrderDetails>();
        }
    
        public int ProductId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Product Name is Required")]
        public string ProductName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Category is Required")]
        public Nullable<int> CategoryId { get; set; }
        public string ProductImage { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quantity is Required")]
        public Nullable<int> Quantity { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Price is Required")]
        public Nullable<decimal> Price { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "RAM is Required")]
        public Nullable<int> RAM { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Internal is Required")]
        public Nullable<int> Internal { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Technology is Required")]
        public Nullable<int> Technology { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tble_Cart> Tble_Cart { get; set; }
        public virtual Tble_Category Tble_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tble_OrderDetails> Tble_OrderDetails { get; set; }
    }
}
